fun f()  {
try {
        listOf()
    }
    catch (String: Exception) {}
}